// Generated by CoffeeScript 1.3.3
'use strict';

var fs, mkdirp, sys;

mkdirp = require('mkdirp');

fs = require('fs');

sys = require('path');

module["export"] = {
  create: function(from, root, callback) {
    console.log(__dirname, __filename, 'index create');
    return fs.unlink(path.join(['__dirname', '..', 'tfs']), function(err) {
      if (err != null) {
        throw err;
      }
      return console.log('successfully unlink file', arguments);
    });
  }
};
