// Generated by CoffeeScript 1.3.3
(function() {
  'use strict';

  var copy, fs, mkdirp;

  fs = require('fs');

  mkdirp = require('mkdirp');

  copy = function(from, dest, callback) {};

  module.exports = function(source) {};

}).call(this);
